# Generated by Django 3.1.5 on 2021-04-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='통화코드')),
                ('name', models.CharField(max_length=50, verbose_name='통화')),
                ('unit', models.CharField(max_length=10, verbose_name='단위')),
                ('status', models.BooleanField(default=False, null=True, verbose_name='사용여부')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'currency_type',
                'verbose_name_plural': 'currency_types',
                'db_table': 'rt_currency_type',
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='결제방식')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'payment_type',
                'verbose_name_plural': 'payment_types',
                'db_table': 'rt_payment_type',
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='ShippingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='배송타입')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'shipping_type',
                'verbose_name_plural': 'shipping_types',
                'db_table': 'rt_shipping_type',
                'ordering': ('-updated',),
            },
        ),
    ]
