# Generated by Django 3.1.5 on 2021-05-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingtype',
            name='fee',
            field=models.IntegerField(default=0, null=True, verbose_name='배송비'),
        ),
    ]
