# Generated by Django 3.1.5 on 2021-05-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_info', '0002_shippingtype_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingtype',
            name='status',
            field=models.BooleanField(default=False, null=True, verbose_name='사용여부'),
        ),
    ]
