# Generated by Django 3.1.5 on 2021-04-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20210424_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='baseDelivery',
            field=models.BooleanField(default=False, verbose_name='기본배송지'),
        ),
    ]
