# Generated by Django 3.1.5 on 2021-05-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_address_basedelivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-id',), 'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
    ]
